name: CI

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: v fmt
        run: |
          cd repo
          v fmt -w .
          git diff --exit-code
      - name: v vet .
        run: |
          cd repo
          v vet .
      - name: Checkout v-csvenc
        uses: actions/checkout@v2
        with:
          path: repo/csvenc
          repository: "https://github.com/takkyuuplayer/v-csvenc.git"
      - name: v-csvenc installation
        run: |
          cd repo/csvenc
          v install
      - name: v test .
        run: |
          cd repo
          v install
          v test .
      - name: v build .
        run: |
          cd repo
          v install
          v -prod .
  docker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: takkyuuplayer/vanki:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  heroku:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tp-v-anki"
          heroku_email: "takkyuuplayer@gmail.com"
          appdir: heroku
          usedocker: true

